name: movil
description: "App inventario Agroveterinario ALEVET"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.4.0
  fl_chart: ^0.69.0
  shared_preferences: ^2.2.3
  http: ^1.2.0
  # firebase_core: ^3.0.0
  # firebase_messaging: ^15.0.0
  # flutter_local_notifications: ^17.0.0
  mobile_scanner: ^5.0.0
  image_picker: ^1.0.7
  intl: 0.20.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true